version: "3.9"

services:
  back-end-demo-api-login-jwt-bycript:
    env_file:
      - .env
    build:
      context: ./backEndDemoAPILoginJWTBycript
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3333:3333"
    depends_on:
      - bd-demo-api-login-jwt-bycript
    volumes:
      - ./backEndDemoAPILoginJWTBycript:/app
    command: npm start



  bd-demo-api-login-jwt-bycript:
    env_file:
    - .env
    build:
      context: ./bdDemoAPILoginJWTBycript
      dockerfile: Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./bdDemoAPILoginJWTBycript/bdDemoAPILoginJWTBycript.sql:/docker-entrypoint-initbd.d/bdDemoAPILoginJWTBycript.sql


  front-end-demo-api-login-jwt-bycript:
    build:
      context: ./frontEndDemoAPILoginJWTBycript
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./frontEndDemoAPILoginJWTBycript/dist/front-end-demo-api-login-jwt-bycript:/usr/share/nginx/html
      - ./frontEndDemoAPILoginJWTBycript/nginx.conf:/etc/nginx/conf.d/default.conf
    image: nginx:1.21.0