version: "3.9"

services:
  backsecretariadesenvolvimentorural:
    env_file:
      - .env
    build:
      context: ./backSecretariaDesenvolvimentoRural
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3333:3333"
    depends_on:
      - bdsecretariadesenvolvimentorural
    volumes:
      - ./backSecretariaDesenvolvimentoRural:/app
    command: npm start



  bdsecretariadesenvolvimentorural:
    env_file:
    - .env
    build:
      context: ./bdSecretariaDesenvolvimentoRural
      dockerfile: Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./bdSecretariaDesenvolvimentoRural/bdSecretariaDesenvolvimentoRural.sql:/docker-entrypoint-initbd.d/bdSecretariaDesenvolvimentoRural.sql


  frontsecretariadesenvolvimentorural:
    build:
      context: ./frontSecretariaDesenvolvimentoRural
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./frontSecretariaDesenvolvimentoRural/dist/front-secretaria-desenvolvimento-rural-jatai:/usr/share/nginx/html
      - ./frontSecretariaDesenvolvimentoRural/nginx.conf:/etc/nginx/conf.d/default.conf
    image: nginx:1.21.0